# Default values for will-playground.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: wil42/playground
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  path: /
  host: app.com

